### ISSUE TITLE
Google Hangouts Chat 

### ISSUE THREAD

**Issue by renanwilliam** [laravel-notification-channels/channels#91]
I would like to integrate notifications to Google Hangouts Chat Rooms

**Comment by atymic** [comment]
AFAIK Hangouts is meant to be shutting down soon, so not sure it's worth having it as a channel?

**Comment by renanwilliam** [comment]
I not referring to classical hangouts, it's the Gsuite Hangouts Chat:
Look at: https://gsuite.google.com/products/chat/

There's no plans to shutting down.

**Comment by atymic** [comment]
Ahh, my bad. Google isn't very clear :)
In that case I'd b happy to have it as a channel. Feel free to clone the skeleton and PR for review :)

**Comment by lucabartoli** [comment]
Edit: my bad. Just saw the PR

Anyone going on here?
Otherwise I will probably create a channel for google chat, based on webhooks

**Comment by frankieeedeee** [comment]
Hey @lucabartoli! Have you started on the Google chat channel? Would be keen to help out if you needed it!

Just for absolute clarification (because Google's name changes for this have been so confusing!!), we're all talking about **Google Chat, circa 2019** (formally Hangouts Chat), which forms a core part of Google Workspace (formally G Suite, formally Google Apps)? 😂

**Relevant Documentation:**
- [Google Chat API](https://developers.google.com/hangouts/chat/concepts)

I assume the implementation would be mono-directional, like most of the other notification channels, and would simply utilise Google Chat's concept of [Incoming Webhooks](https://developers.google.com/hangouts/chat/how-tos/webhooks)?

@atymic Can we rename this issue to 'Google Chat'?

**Comment by renanwilliam** [comment]
https://github.com/laravel-notification-channels/google-chat
